TEST_VALUE:
  name: "dev_cookie"

APP_TOKEN_CACHE_KEY: APP_TOKEN_CACHE_KEY
USER_TOKEN_CACHE_KEY: feishu_user_token__

FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: cli_a25d66a31fba900b
  FEISHU_APP_SECRET: qRGqTouHXcxw70mpKvNAScI6dmbYsU1m
  FEISHU_API_OAUTH: https://passport.feishu.cn/suite/passport/oauth

MYSQL_CONFIG:
  name: "zmj"
  type: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "123456"
  database: "test"
  entities: "mysql" # 这里的命名一定要跟 MongoDB 里面的配置命名区分开
  synchronize: true

REDIS_CONFIG:
  host: "localhost"  # redis 链接
  port: 6379         # redis 端口
  auth: "123456"           # redis 连接密码
  db: 0              # redis 数据库