TEST_VALUE:
  name: "dev_cookie"

MYSQL_CONFIG:
  name: "zmj"
  type: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "123456"
  database: "test1"
  entities: "mysql"
  synchronize: true

USER_MICROSERVICES:
  host: "0.0.0.0"
  port: 4100